-- https://school.programmers.co.kr/learn/courses/30/lessons/131533
SELECT A.PRODUCT_CODE
     , SUM(B.SALES_AMOUNT * A.PRICE) AS 'SALES'
FROM PRODUCT A JOIN OFFLINE_SALE B
WHERE A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, A.PRODUCT_CODE ASC;
